apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshotClass
metadata:
  name: unity-snapclass
snapshotter: csi-unity.dellemc.com
parameters:
{{ if .Values.snapshotRetentionDuration }}
  retentionDuration: {{ .Values.snapshotRetentionDuration }}
{{ end }}
{{ if .Values.isSnapshotReadOnly }}
  isReadOnly: {{ .Values.snapshotIsReadOnly | default "false" | lower | quote }}
{{ end }}
