apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshotClass
metadata:
  name: unity-snapclass
snapshotter: csi-unity.dellemc.com
parameters:
{{ if .Values.snapshotRetentionDuration }}
  retentionDuration: {{ .Values.snapshotRetentionDuration | default "" | quote  }}
{{ else if .Values.snapshotClass.retentionDuration }}
  retentionDuration: {{ .Values.snapshotClass.retentionDuration | default "" | quote  }}
{{ end }}

