{{ $global := . }}
{{- range $i, $v := .Values.storageArrayList }}
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshotClass
metadata:
  {{- if $v.isDefaultArray }}
  name: "unity-snapclass"
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: {{ $v.isDefaultArray | quote }}
  {{ else }}
  name: {{ "unity" }}-{{ $v.name | lower }}-snapclass
  {{- end }}
snapshotter: csi-unity.dellemc.com
parameters:
  retentionDuration: {{ $v.snapshotClass.retentionDuration | default "" | quote  }}
---
{{- end }}

