# "restGateway" defines the Unity REST API endpoint, with full URL, typically leveraging HTTPS.
# You must set this for your Unity installations REST gateway.
# restGateway: https://123.0.0.1

# "storagePool" defines the Unity storage pool from which this driver will # provision volumes.
# You must set this for the primary storage pool to be used
# storagePool: sp

# "volumeNamePrefix" defines a string prepended to each volume created by the CSI driver.
volumeNamePrefix: csivol

# "snapNamePrefix" defines a string prepended to each snapshot registered by the CSI driver.
snapNamePrefix: csi-snap

# "unityInsecure" determines if the driver is going to validate unisphere certs while
# connecting to the Unisphere RESTAPI interface
# If it is set to false, then a secret unity-certs has to be created with a X.509 certificate of CA
# which signed the Unisphere certificate
unityInsecure: "true"

# To set the debug log policy for CSI driver
csiDebug: "false"

# The default pull policy is IfNotPresent which causes the Kubelet to skip pulling an image
# if it already exists. If you would like to always force a pull, use "Always"
imagePullPolicy: IfNotPresent

# The installation process will generate multiple storageclasses based on these parameters.
# Only the primary storageclass for the driver will be marked default if specified.
storageClass:
  # "storageClass.name" defines the name of the storage class to be defined.
  name: unity

  # "storageClass.isDefault" defines whether the primary storage class should be the # default.
  isDefault: "true"

  # "storageClass.reclaimPolicy" defines what will happen when a volume is
  # removed from the Kubernetes API. Valid values are "Retain" and "Delete".
  reclaimPolicy: Delete

# The installation process will generate snapshotClasses based on these parameters.
snapshotClass:
  #To set snapshot retention duration. Format:"1:23:52:50" (number of days:hours:minutes:sec)
  retentionDuration: ""

# IT IS RECOMMENDED YOU DO NOT CHANGE THE IMAGES TO BE DOWNLOADED.
images:
  # "images.driver" defines the container images used for the driver container.
  driver: dellemc/csi-unity:v1.1.0.000R

  # "images.attacher" defines the container images used for the csi attacher
  # container.
  attacher: quay.io/k8scsi/csi-attacher:v1.2.1

  # "images.provisioner" defines the container images used for the csi provisioner
  # container.
  #provisioner: quay.io/k8scsi/csi-provisioner:v0.4.2 #for CSI 0.3.0 only (obsolete)
  provisioner: quay.io/k8scsi/csi-provisioner:v1.2.1

  # "images.snapshotter" defines the container image used for the csi snapshotter
  snapshotter: quay.io/k8scsi/csi-snapshotter:v1.2.2

  # "images.registrar" defines the container images used for the csi registrar
  # container.
  registrar: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0

